FROM alpine:3.9

LABEL maintainer="Andrius Kairiukstis <k@andrius.mobi>"

ENV NOKOGIRI_USE_SYSTEM_LIBRARIES=1

ADD gemrc /root/.gemrc

RUN apk update \
&& apk add ruby \
           ruby-bigdecimal \
           ruby-io-console \
           ruby-irb \
           ca-certificates \
           libressl \
           less \
&& apk add --virtual build-dependencies \
           build-base \
           ruby-dev \
           libressl-dev \
\
&& gem install --no-rdoc --no-ri bundler:'~> 2.0' \
                                 json \
&& bundle config build.nokogiri --use-system-libraries \
&& bundle config git.allow_insecure true \
\
&& gem cleanup \
&& apk del build-dependencies \
&& rm -rf /usr/lib/ruby/gems/*/cache/* \
          /var/cache/apk/* \
          /tmp/* \
          /var/tmp/*
