# vim:set ft=dockerfile:
FROM andrius/alpine-ruby:3.4

MAINTAINER Andrius Kairiukstis <andrius@kairiukstis.com>

RUN apk add --update less curl wget git ruby-dev build-base \
&& rm -rf /var/cache/apk/*

