# vim:set fenc=utf-8 ts=2 sw=2 sts=2 et ft=dockerfile:
ARG ALPINE_VERSION
FROM frolvlad/alpine-glibc:alpine-${ALPINE_VERSION}

LABEL "org.opencontainers.image.authors"="Andrius Kairiukstis <k@andrius.mobi>"
LABEL "org.opencontainers.image.source"="https://github.com/andrius/alpine-ruby"
LABEL "org.opencontainers.image.description"="Minimal dockerized ruby based on frolvlad/alpine Linux (Alpine with GNU C library - glibc)"

RUN apk --no-cache add bash

SHELL ["/bin/bash", "-c"]

RUN apk --no-cache add \
  ca-certificates \
  less \
  libressl \
  ruby \
  ruby-bigdecimal \
  ruby-etc \
  ruby-io-console \
  ruby-irb

COPY gemrc /root/.gemrc

# The following is needed for nokogiri
ENV NOKOGIRI_USE_SYSTEM_LIBRARIES=1

# It tries to install ruby bundler with failback to apk version and nokoiri
RUN <<EOF
apk add --no-cache --virtual .build-dependencies build-base ruby-dev libressl-dev 
ERR=$(gem install bundler 2>&1);
if [[ $ERR =~ \`(.+)\` ]]; then 
  eval "${BASH_REMATCH[1]} 2>&1"
fi || apk add ruby-bundler
gem install json
bundle config build.nokogiri --use-system-libraries
bundle config git.allow_insecure true
gem cleanup
rm -rf /usr/lib/ruby/gems/*/cache/*
apk del .build-dependencies 
EOF

