name: Build and Push Docker Images

on:
  push:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *' # runs every day at midnight
#
defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-${{ github.workflow_ref }}-${{ matrix.alpine_version }}-build
      cancel-in-progress: false
    timeout-minutes: 60
    strategy:
      max-parallel: 64
      fail-fast: false
      matrix:
        alpine_version:
          - latest
          - edge
          - 3.8
          - 3.9
          - 3.10
          - 3.11
          - 3.12
          - 3.13
          - 3.14
          - 3.15
          - 3.16
          - 3.17
          - 3.18
          - 3.19

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: docker login -u andrius -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          if [ -f "Dockerfile-${{ matrix.alpine_version }}" ]; then
            DOCKERFILE="Dockerfile-${{ matrix.alpine_version }}"
          else
            DOCKERFILE="Dockerfile"
          fi

          docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64 \
            --tag andrius/alpine-ruby:${{ matrix.alpine_version }} \
            --build-arg ALPINE_VERSION=${{ matrix.alpine_version }} \
            --file $DOCKERFILE \
            .

      - name: Build and push glibc image
        run: |
          if [ -f "Dockerfile-${{ matrix.alpine_version }}" ]; then
            DOCKERFILE="Dockerfile-glibc-${{ matrix.alpine_version }}"
          else
            DOCKERFILE="Dockerfile-glibc"
          fi

          docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64 \
            --tag andrius/alpine-ruby:${{ matrix.alpine_version }} \
            --build-arg ALPINE_VERSION=${{ matrix.alpine_version }} \
            --file $DOCKERFILE \
            .
